version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-test-coverage:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests and create coverage
          command: yarn lerna run test:coverage
      - run:
          name: Upload coverage to codecov
          command: yarn lerna exec -- yarn codecov -F \$LERNA_PACKAGE_NAME --token="${CODECOV_TOKEN}"

workflows:
  build-test-coverage:
    jobs:
      - build-test-coverage
